[W2][D2][다람이&징징이] 프론트엔드 세팅
boostcampwm-2021/web20-PingPingsFriends pull request #8
Opened 2021-11-02 11:10 UTC by kanghohyeong

### 작업 내역
---
- [x] CRA 초기화
- [x] Dockerfile 작성

### 고민 및 해결
---
1. 페키지 메니저 npm 대신 yarn 사용(강제적) : 기본적으로 CRA가 yarn을 쓰고, yarn이 설치가 빨라서 docker 환경에 유리함. 또 npm과 혼용시 충돌 가능성 있음.
2. prettier 설정이 특정 시점에 모든 파일에 적용되어 포멧이 모두 동일함을 보장해야 할 것 같다.
3. 디렉토리 구조
    - 라우팅 되는 페이지에 대한 컴포넌트 : `pages`
    - 그 외 컴포넌트들 :  `components` - 기능별로 하위 디렉토리 생성
4. 포트
    - 개발 시 : 8080 (react server)
    - 배포 시 : 80 (nginx)
5. react-app-env.d.ts : 추가 학습 필요
6. docker image : multistage-build 사용

2021-11-02 11:13 UTC, ludacirs commented
고생하셨습니다.

2021-11-03 01:23 UTC, 9b2n commented on front/.env
> +PORT=8080
EOF 에러가 발생했네요 [EOF 관련 자료](https://minz.dev/19)
prettier 설정 파일에서 {"endOfLine": "auto" } 설정을 넣으시면 해결할 수 있습니다.
저희도 추가해야겠네요 ㅎㅎ;

2021-11-03 01:23 UTC, 9b2n commented on front/package.json
> -      "react-app/jest"
react-app/jest를 삭제한 이유가 오류때문인가요?

2021-11-03 01:40 UTC, ludacirs commented on front/package.json
> -      "react-app/jest"
네 맞습니다.
https://stackoverflow.com/questions/58065765/eslint-jest-globals-environment-key-unknown

2021-11-03 01:42 UTC, ludacirs requested changes

2021-11-03 01:42 UTC, ludacirs commented on front/.prettierrc
> +    "bracketSpacing": true,
"endOfLine": "auto"

2021-11-03 02:10 UTC, ludacirs approved these changes

2021-11-03 02:10 UTC, ludacirs commented on front/.prettierrc
> +    "bracketSpacing": true,
```suggestion
    "bracketSpacing": true,
    "endOfLine": "auto"
```

2021-11-03 02:25 UTC, kanghohyeong commented on front/.prettierrc
> +    "bracketSpacing": true,
이 설정만으로 해결되지 않네요.. `.env` 파일에 줄바꿈이 적용되지 않아요. 
깃 관련 설정을 해야 커밋시에 끝줄 추가 자동으로 될 것 같습니다.
아니면 에디터 설정을 해야할 것 같습니다
https://prettier.io/docs/en/options.html#end-of-line

2021-11-03 04:55 UTC, merged